name: example
services:
  admin_webserver:
    container_name: admin_panel
    build: ./php-fpm/
    volumes:
      - ../website/admin/:/var/www/html/
    networks:
      - example

  app_webserver:
    container_name: web_app
    build: ./php-fpm/
    volumes:
      - ../website/app/:/var/www/html/
    networks:
      - example
  
  landing_webserver:
    container_name: landing_page
    build: ./php-fpm/
    volumes:
      - ../website/main/:/var/www/html/
    networks:
      - example

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - admin_webserver
      - app_webserver
      - landing_webserver
    networks:
      - example
    
  postgresql:
    image: postgres:14.21-alpine3.23
    container_name: postgresql
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pg_volume:/var/lib/postgresql/data/:rw
      - ./postgre/init/:/docker-entrypoint-initdb.d/:ro
      # - ./postgre/postgres.conf:/etc/postgresql/postgresql.conf:ro
      #  "-c", "config_file=/etc/postgresql/postgresql.conf", 
    command: [ "postgres", "-c", "log_statement=none", "-c", "log_min_duration_statement=1000", "-c", "log_connections=on", "-c", "log_disconnections=on" ]   
    healthcheck:
      test: [ "CMD-SHELL", 'pg_isready -U "$${POSTGRES_USER:-postgres}" -d "$${POSTGRES_DB:-postgres}" -h localhost || exit 1' ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    stop_grace_period: 120s
    networks:
      - example

  pgadmin:
    image: dpage/pgadmin4
    container_name: mypgadmin
    env_file:
      - .env
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      postgresql:
        condition: service_healthy
    links:
      - postgresql
    networks:
      - example

  mysql:
    container_name: mysql_db
    image: mysql:latest
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
#     - ./docker/data/conf.d:/etc/mysql/conf.d
#     - ./docker/data/logs:/logs
      - ./mysql:/docker-entrypoint-initdb.d
      - mysql_volume:/var/lib/mysql
    networks:
      - example

  phpmyadmin:
    container_name: phpMyAdmin
    image: phpmyadmin/phpmyadmin
    env_file: .env
    ports:
      - "8082:80"
    depends_on:
      - mysql
    networks:
      - example


  # phppgadmin:
  #   restart: always
  #   container_name: PhpPgAdmin
  #   image: dockage/phppgadmin:latest
  #   ports:
  #     - "8081:80"
  #     - "8082:443"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgresql
  #   networks:
  #     - example

  sessions-cache:
    image: redis:7.4-alpine
    container_name: Redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass yourpassword
    volumes:
      - cache:/data
    networks:
      - example

networks:
  example:
    driver: bridge

volumes:
  pg_volume:
    driver: local
  cache:
    driver: local
  mysql_volume:
    driver: local
  pgadmin-data:
    driver: local